"use client";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";

export default function LoginPage() {
  const router = useRouter(); const params = useSearchParams();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [missing,setMissing]=useState(false); const [busy,setBusy]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");setMissing(false);const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Login failed");setMissing(d.code==="ACCOUNT_NOT_FOUND");return;}router.replace(params.get("next")||"/");router.refresh();};
  return <main className="flex h-full items-center justify-center p-6"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900/70 p-7 shadow-2xl"><div className="mb-6"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl border border-sky-500/30 bg-sky-500/10 font-black text-sky-400">NX</div><h1 className="text-2xl font-bold text-white">Sign in to NEXUS</h1><p className="mt-2 text-sm text-slate-500">Protected operations console</p></div>{error&&<div className="mb-4 rounded-xl border border-red-900/60 bg-red-950/30 p-3 text-sm text-red-300">{error}{missing&&<> <Link className="font-semibold underline" href="/signup">Create an account</Link>.</>}</div>}<form onSubmit={submit} className="space-y-4"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-sky-500"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-sky-500"/><button disabled={busy} className="w-full rounded-xl bg-sky-500 py-3 text-sm font-bold text-slate-950 disabled:opacity-50">{busy?"Signing in…":"Sign in"}</button></form><div className="mt-5 flex justify-between text-xs"><Link className="text-slate-500 hover:text-white" href="/reset-password">Forgot password?</Link><Link className="text-sky-400 hover:text-sky-300" href="/signup">Create account</Link></div></div></main>;
}
